CREATE OR REPLACE WAREHOUSE DEV_XS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE RESOURCE MONITOR DEV_MONITOR
  WITH CREDIT_QUOTA = 20
  FREQUENCY = MONTHLY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE DEV_XS_WH SET RESOURCE_MONITOR = DEV_MONITOR;
