CREATE OR REPLACE DATABASE ENTERPRISE_COPILOT_DEV;

CREATE OR REPLACE SCHEMA ENTERPRISE_COPILOT_DEV.RAW;
CREATE OR REPLACE SCHEMA ENTERPRISE_COPILOT_DEV.STAGING;
CREATE OR REPLACE SCHEMA ENTERPRISE_COPILOT_DEV.INTEGRATION;
CREATE OR REPLACE SCHEMA ENTERPRISE_COPILOT_DEV.MARTS;
CREATE OR REPLACE SCHEMA ENTERPRISE_COPILOT_DEV.SEMANTIC;
CREATE OR REPLACE SCHEMA ENTERPRISE_COPILOT_DEV.AUDIT;
CREATE OR REPLACE SCHEMA ENTERPRISE_COPILOT_DEV.APP;

CREATE OR REPLACE ROLE APP_ANALYST;
CREATE OR REPLACE ROLE APP_MANAGER;
CREATE OR REPLACE ROLE APP_ADMIN;
CREATE OR REPLACE ROLE APP_AUDITOR;

GRANT USAGE ON DATABASE ENTERPRISE_COPILOT_DEV TO ROLE APP_ANALYST;
GRANT USAGE ON DATABASE ENTERPRISE_COPILOT_DEV TO ROLE APP_MANAGER;
GRANT USAGE ON DATABASE ENTERPRISE_COPILOT_DEV TO ROLE APP_ADMIN;
GRANT USAGE ON DATABASE ENTERPRISE_COPILOT_DEV TO ROLE APP_AUDITOR;
