USE DATABASE ENTERPRISE_COPILOT_DEV;

-- Create a stage and upload generated CSV files before running COPY INTO.
-- Example from SnowSQL:
-- CREATE OR REPLACE STAGE RAW.SYNTHETIC_STAGE;
-- PUT file://data/raw/*.csv @RAW.SYNTHETIC_STAGE AUTO_COMPRESS=TRUE;

CREATE OR REPLACE FILE FORMAT RAW.SYNTHETIC_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null');

COPY INTO RAW.RAW_ORACLE_SUPPLIERS
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_SUPPLIERS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_SUPPLIER_SITES
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_SUPPLIER_SITES.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_PO_HEADERS
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_PO_HEADERS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_PO_LINES
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_PO_LINES.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_PO_DISTRIBUTIONS
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_PO_DISTRIBUTIONS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_RECEIPTS
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_RECEIPTS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_AP_INVOICES
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_AP_INVOICES.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_AP_INVOICE_LINES
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_AP_INVOICE_LINES.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_AP_PAYMENTS
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_AP_PAYMENTS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_ORACLE_GL_CODE_COMBINATIONS
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_GL_CODE_COMBINATIONS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_SUPPLIERS
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_SUPPLIERS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_REQUISITIONS
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_REQUISITIONS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_REQUISITION_LINES
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_REQUISITION_LINES.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_PURCHASE_ORDERS
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_PURCHASE_ORDERS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_PURCHASE_ORDER_LINES
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_PURCHASE_ORDER_LINES.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_RECEIPTS
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_RECEIPTS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_INVOICES
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_INVOICES.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_APPROVALS
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_APPROVALS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_USERS
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_USERS.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;

COPY INTO RAW.RAW_COUPA_COMMODITIES
FROM @RAW.SYNTHETIC_STAGE/RAW_COUPA_COMMODITIES.csv.gz
FILE_FORMAT = RAW.SYNTHETIC_CSV;
