USE DATABASE ENTERPRISE_COPILOT_DEV;

-- Create a stage and upload generated CSV files before running COPY INTO.
-- Example:
-- CREATE OR REPLACE STAGE RAW.SYNTHETIC_STAGE;
-- PUT file://data/raw/RAW_ORACLE_SUPPLIERS.csv @RAW.SYNTHETIC_STAGE AUTO_COMPRESS=TRUE;

COPY INTO RAW.RAW_ORACLE_SUPPLIERS
FROM @RAW.SYNTHETIC_STAGE/RAW_ORACLE_SUPPLIERS.csv.gz
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
