USE DATABASE ENTERPRISE_COPILOT_DEV;

CREATE OR REPLACE VIEW MARTS.MART_PROCUREMENT_SPEND AS
SELECT business_unit, commodity, COUNT(*) AS purchase_order_count, SUM(po_amount) AS total_po_amount
FROM RAW.RAW_COUPA_PURCHASE_ORDERS
GROUP BY business_unit, commodity;

CREATE OR REPLACE VIEW MARTS.MART_INVOICE_EXCEPTIONS AS
SELECT *
FROM MARTS.DT_MART_INVOICE_EXCEPTIONS;
