USE DATABASE ENTERPRISE_COPILOT_DEV;

CREATE OR REPLACE MASKING POLICY APP.MASK_TAX_ID AS (val STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('APP_ADMIN') THEN val ELSE '***-**-' || RIGHT(val, 4) END;

CREATE OR REPLACE MASKING POLICY APP.MASK_BANK_ACCOUNT AS (val STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('APP_ADMIN') THEN val ELSE '********' || RIGHT(val, 4) END;

CREATE OR REPLACE MASKING POLICY APP.MASK_EMAIL AS (val STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('APP_ADMIN') THEN val ELSE REGEXP_REPLACE(val, '^(.).*(@.*)$', '\\1***\\2') END;

CREATE OR REPLACE MASKING POLICY APP.MASK_PHONE AS (val STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('APP_ADMIN') THEN val ELSE '(***) ***-' || RIGHT(REGEXP_REPLACE(val, '[^0-9]', ''), 4) END;
