USE DATABASE ENTERPRISE_COPILOT_DEV;

CREATE OR REPLACE ROW ACCESS POLICY APP.BUSINESS_UNIT_ACCESS AS (business_unit STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('APP_ADMIN', 'APP_AUDITOR')
  OR business_unit IS NOT NULL;

-- Example:
-- ALTER TABLE RAW.RAW_ORACLE_AP_INVOICES ADD ROW ACCESS POLICY APP.BUSINESS_UNIT_ACCESS ON (business_unit);
